AllCops:
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - bin/*

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  EnforcedStyle: semantic
