version: '3.1'

networks:
  net:

services:
  web:
    image: fooda
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - web
